title: Emrie Loh
description: Personal website featuring coding projects, teaching resources, research materials,and professional information.
author: Emrie Loh
github_username: ELOH53

# Navigation
navigation:
  - title: Home
    url: /
  - title: Teaching
    url: /teaching.html
  - title: Research
    url: /research.html
  - title: Projects
    url: /projects.html
  - title: CV
    url: /cv.html


# Build settings
# Using custom layout, so no theme needed
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
